version: ‘3’

services:
  mariadb:
    image: mariadb
    container_name: mariadb			    # Le nom du container, oui vraiment.
    build:
      context: requirements/mariadb # ou se trouve son Dockerfile
      dockerfile: Dockerfile			  # le nom du Dockerfile ?!
    env_file: .env                  # le fichier d'environnement pour transmettre les variables
    networks:
      - inception            			  # à quel network il appartient
    volumes:                        # Voir plus bas
      - mariadb:/var/lib/mysql
    restart: unless-stopped         # redémarre tant qu'il n'est pas stoppé
    expose:                         # le port à exposer
      - "3306"

  nginx:
    image: nginx
    container_name: nginx
    build:
      context:  requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    volumes:
			- wordpress:/var/www/wordpress
    depends_on:        			          # Nouvelle ligne, indiquant de ne pas démarrer NGINX tant que WordPress n'a pas démarré.
		  - wordpress
    port: "443:443"                   # on indique le port qui sera exposé a la machine locale
    restart: on_failure               # Ici nous changeons, le container redémarrera uniquement en cas de crash.

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context:  requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    networks:
      - inception
    volumes:
	    - wordpress:/var/www/wordpress
    depends_on:
      - mariadb
    expose:
      - "9000"
    restart: on_failure
