version: '3'

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: requirements/mariadb/
    volumes:
      - mariadb:/var/lib/mysql/
    networks:
      - inception
    expose:
      - "3306"
    env_file: .env
    restart: on-failure
  
  nginx:
    container_name: nginx
    image: nginx
    depends_on:
      - wordpress
    build: 
      context: requirements/nginx/
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    ports:
      - "443:443"
    env_file: .env
    restart: on-failure

  wordpress:
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    build: requirements/wordpress/
    volumes:
      - wordpress:/var/www/html/
    networks:
      - inception
    restart: on-failure
    expose:
      - "9000"
    env_file: .env
  
volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/mat/data/wordpress'
  
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: '/home/mat/data/mariadb'

networks:
  inception:
    driver: bridge
